// Builds life-planner/world.js (country outlines for the Travel map) from the public-domain Natural Earth
// data in the "world-atlas" npm package. Run from a scratch folder where these are installed:
//   npm i world-atlas topojson-client d3-geo
//   node build_world_map.mjs > /path/to/life-planner/world.js
import { createRequire } from "module";
import { feature } from "topojson-client";
import { geoNaturalEarth1, geoPath } from "d3-geo";
const require = createRequire(import.meta.url);
const topo = require("world-atlas/countries-110m.json");
const all = feature(topo, topo.objects.countries);
const land = { type: "FeatureCollection", features: all.features.filter((f) => f.properties.name !== "Antarctica") };
const W = 1000, H = 520;
const projection = geoNaturalEarth1().fitExtent([[4, 4], [W - 4, H - 4]], land);
const path = geoPath(projection).digits(1);
const rows = land.features.map((f) => [f.properties.name, path(f)]).filter((r) => r[1]);
console.log("/* Country outlines for the Travel map. Generated by tools/build_world_map.mjs from Natural Earth (public domain). */");
console.log("window.LIFE_WORLD = " + JSON.stringify({ w: W, h: H, countries: rows }) + ";");
